# Generated by Django 4.0.4 on 2022-05-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac_electronica', '0001_CreacionT_Pedido_DetallePedido_Comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='propina',
        ),
    ]
