# Generated by Django 4.0.4 on 2022-04-25 03:49

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('precio', models.FloatField()),
                ('foto1', cloudinary.models.CloudinaryField(max_length=255)),
                ('foto2', cloudinary.models.CloudinaryField(max_length=255)),
                ('foto3', cloudinary.models.CloudinaryField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'muebles',
            },
        ),
        migrations.CreateModel(
            name='ListaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precio_diario', models.FloatField()),
                ('muebleId', models.ForeignKey(db_column='lista_producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='lista_productos', to='lista_producto.mueble')),
            ],
            options={
                'db_table': 'lista_productos',
                'unique_together': {('fecha', 'muebleId')},
            },
        ),
    ]
