# Generated by Django 4.0.4 on 2022-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_producto', '0001_CreacionT_Mueble_ListProd'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='categoria',
            field=models.CharField(choices=[['SALA', 'SALA'], ['COMEDOR', 'COMEDOR'], ['DORMITORIO', 'DORMITORIO'], ['JARDIN', 'JARDIN']], max_length=15, null=True),
        ),
    ]
