# Generated by Django 4.0.4 on 2022-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_producto', '0002_change_categoria_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='categoria',
            field=models.CharField(choices=[['SALA', 'SALA'], ['COCINA', 'COCINA'], ['COMEDOR', 'COMEDOR'], ['DORMITORIO', 'DORMITORIO'], ['JARDIN', 'JARDIN']], max_length=15, null=True),
        ),
    ]
