# Generated by Django 4.0.4 on 2022-05-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_producto', '0005_Creacion_Tabla_Picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muebles',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='muebles',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='muebles',
            name='foto3',
        ),
    ]
